name: Daily Weather ETL to Supabase

on:
  schedule:
    - cron: '0 3 * * *'  # каждый день в 06:00 МСК
  workflow_dispatch:     # можно запускать вручную

jobs:
  etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run ETL script (Open-Meteo → Supabase)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python actions_etl_weather_current_from_open_meteo.py
